[package]
name = "discord_bot"
version = "0.1.0"
authors = ["Stuart <stu@reilly-family.co.uk>"]

[dependencies]
serenity = "0.5"
config = "0.8"
directories = "0.10"
failure = "0.1"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
rand = "0.4"
